apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
spec:
  selector:
    matchLabels:
      app: website
  replicas: 4
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: erfanseidipoor/argo-website:v2
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: website-service
spec:
  selector:
    app: website
  ports:
  - port: 7004
    protocol: TCP
    targetPort: 3000


